### ISSUE TITLE
Confirm Twitter API Keys?

### ISSUE THREAD

**Issue by johnny2678** [xoelop/get-twitter-likes#24]
Cool project!  Got the whole thing set up and pulled my first 4000 tweet likes back. Only when I viewed them in Tinybird I had never seen any of the tweets before and half of them are in a language I don't speak 😂

Can you confirm that the Twitter API keys/secrets in the `.env` should come from this location on `developer.twitter.com`?
```
TWITTER_API_KEY=...
TWITTER_API_SECRET=...
TWITTER_ACCESS_TOKEN=...
TWITTER_ACCESS_TOKEN_SECRET=...
```
![image](https://user-images.githubusercontent.com/8219743/195601543-3ee47c52-51a9-4790-8a52-a861c7bbcfa1.png)

If so, I have no idea whose tweets I'm looking at.

**Comment by johnny2678** [comment]
aha!  Just noticed your username is hardcorded in src/core.py

Easy fix!  I'll probably make this part of `.env`

https://github.com/xoelop/get-twitter-likes/blob/b5ea7c6fdbf0eee8cfd549921f1dbf5d91143742/src/core.py#L253
and
https://github.com/xoelop/get-twitter-likes/blob/b5ea7c6fdbf0eee8cfd549921f1dbf5d91143742/src/core.py#L255

Thanks again!

**Comment by xoelop** [comment]
Feel free to send a PR! :)
